package com.lemarket.data.dao;

import com.lemarket.data.model.Address;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    List<Address> selectAll();

    //获取个人全部收货地址
    List<Address> selectAllByUserId(@Param("userId") int userId);

    //获取个人某个收货地址
    Address selectByUserIdAndId(@Param("userId") int userId, @Param("id") int id);

    //更改收货地址
    int updateAddress(Address re);

}