package com.lemarket.data.dao;

import com.lemarket.data.model.Address;
import java.util.List;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Address
     *
     * @mbg.generated
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Address
     *
     * @mbg.generated
     */
    List<Address> selectAll();
}