package com.lemarket.data.dao;

import com.lemarket.data.model.Admin;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Admin
     *
     * @mbg.generated
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Admin
     *
     * @mbg.generated
     */
    List<Admin> selectAll();

    Admin selectByUsername(String username);
}