package com.lemarket.data.dao;

import com.lemarket.data.model.Commodity;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Commodity
     *
     * @mbg.generated
     */
    int insert(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Commodity
     *
     * @mbg.generated
     */
    List<Commodity> selectAll();

    List<Commodity> selectBySaledOrder();

    Commodity selectById(int id);

    List<Commodity> selectPageByKindAndSaled(int category);

    List<Commodity> selectByShopId(int shopId, int beginRow, int pageSize);

    List<Commodity> selectByName(String word);
}