package com.lemarket.data.dao;

import com.lemarket.data.model.Commodity;
import com.lemarket.data.model.CommodityWithShop;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Commodity
     *
     * @mbg.generated
     */
    int insert(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Commodity
     *
     * @mbg.generated
     */
    List<Commodity> selectAll();

    List<Commodity> selectBySaledOrder();

    Commodity selectById(int id);

    List<Commodity> selectPageByKindAndSaled(@Param("category") int category, @Param("beginRow") int beginRow, @Param("pageSize") int pageSize);

    List<Commodity> selectByShopId(int shopId, int beginRow, int pageSize);

    List<Commodity> selectByName(String word);

    int selectCountById(int category);

    CommodityWithShop selectCommodityWithShopByCommodityId(int id);

    //更新图标
    int updateImage(int imageId, int commodityId);

    //更新商品
    int updateCommodity(Commodity newCommodity);
}