package com.lemarket.data.dao;

import com.lemarket.data.model.Information;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface InformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Information
     *
     * @mbg.generated
     */
    int insert(Information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Information
     *
     * @mbg.generated
     */
    List<Information> selectAll();
}