package com.lemarket.data.dao;

import com.lemarket.data.model.OrderWithDetail;
import com.lemarket.data.model.Orderinfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OrderinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderInfo
     *
     * @mbg.generated
     */
    int insert(Orderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderInfo
     *
     * @mbg.generated
     */
    List<OrderWithDetail> selectAll();

    //获取用户订单
    List<OrderWithDetail> selectByUserIdAndStatus(@Param("id") int id, @Param("status") String status, @Param("beginRow") int beginRow, @Param("pageSize") int pageSize);

    List<OrderWithDetail> selectAllById(@Param("id") int id, @Param("beginRow") int beginRow, @Param("pageSize") int pageSize);
    int selectLast();

    int updateStatusById(@Param("status") String status, @Param("id") int id);
    //删除订单
    int deleteOrderByOrderId(@Param("id") int id);

    //获取店铺订单状态
    List<OrderWithDetail> selectOrderByShopIdAndStatus(@Param("shopId") int shopId, @Param("status") String status, @Param("beginRow") int beginRow, @Param("pageSize") int pageSize);
}