package com.lemarket.data.dao;

import com.lemarket.data.model.Orderinfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OrderinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderInfo
     *
     * @mbg.generated
     */
    int insert(Orderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderInfo
     *
     * @mbg.generated
     */
    List<Orderinfo> selectAll();

    //获取用户订单
    List<Orderinfo> selectByUserIdAndStatus(int id, String status, int beginRow, int pageSize);

    List<Orderinfo> selectAllById(int id, int beginRow, int pageSize);
    int selectLast();

    int updateStatusById(String status,int id);
    //删除订单
    int deleteOrderByOrderId(int id);

    //获取店铺订单状态
    List<Orderinfo> selectOrderByShopIdAndStatus(int shopId, String status, int beginRow, int pageSize);
}