package com.lemarket.data.dao;

import com.lemarket.data.model.Picture;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Picture
     *
     * @mbg.generated
     */
    int insert(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Picture
     *
     * @mbg.generated
     */
    List<Picture> selectAll();

    Picture selectById(@Param("id") int id);
    Picture selectByPath(@Param("path") String path);

    int deleteById(@Param("id") int id);
    Picture updateImageById(@Param("path") String path, @Param("id") int id);
}