package com.lemarket.data.dao;

import com.lemarket.data.model.Picture;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Picture
     *
     * @mbg.generated
     */
    int insert(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Picture
     *
     * @mbg.generated
     */
    List<Picture> selectAll();

    Picture selectById(int id);
    Picture selectByPath(String path);

    int deleteById(int id);
}