package com.lemarket.data.dao;

import com.lemarket.data.model.Receiveinfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ReceiveinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ReceiveInfo
     *
     * @mbg.generated
     */
    int insert(Receiveinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ReceiveInfo
     *
     * @mbg.generated
     */
    List<Receiveinfo> selectAll();

    int selectLast();
}