package com.lemarket.data.dao;

import com.lemarket.data.model.Token;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Token
     *
     * @mbg.generated
     */
    int insert(Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Token
     *
     * @mbg.generated
     */
    List<Token> selectAll();

    Token selectById(int id);

    int deleteById(int id);

<<<<<<< HEAD
    Token selectByToken(String token);
=======
    int selectUserById(int id);


>>>>>>> 30f961079f21efa22c1973dc4df95bf324f684b8
}