package com.lemarket.data.dao;

import com.lemarket.data.model.Usertype;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UsertypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserType
     *
     * @mbg.generated
     */
    int insert(Usertype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserType
     *
     * @mbg.generated
     */
    List<Usertype> selectAll();
}