package com.lemarket.data.model;

public class Commoditytype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CommodityType.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CommodityType.commodity
     *
     * @mbg.generated
     */
    private Integer commodity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CommodityType.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CommodityType.id
     *
     * @return the value of CommodityType.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CommodityType.id
     *
     * @param id the value for CommodityType.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CommodityType.commodity
     *
     * @return the value of CommodityType.commodity
     *
     * @mbg.generated
     */
    public Integer getCommodity() {
        return commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CommodityType.commodity
     *
     * @param commodity the value for CommodityType.commodity
     *
     * @mbg.generated
     */
    public void setCommodity(Integer commodity) {
        this.commodity = commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CommodityType.name
     *
     * @return the value of CommodityType.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CommodityType.name
     *
     * @param name the value for CommodityType.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}