package com.lemarket.data.model;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Message.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Message.sender
     *
     * @mbg.generated
     */
    private Integer sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Message.reciver
     *
     * @mbg.generated
     */
    private Integer reciver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Message.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Message.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Message.id
     *
     * @return the value of Message.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Message.id
     *
     * @param id the value for Message.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Message.sender
     *
     * @return the value of Message.sender
     *
     * @mbg.generated
     */
    public Integer getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Message.sender
     *
     * @param sender the value for Message.sender
     *
     * @mbg.generated
     */
    public void setSender(Integer sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Message.reciver
     *
     * @return the value of Message.reciver
     *
     * @mbg.generated
     */
    public Integer getReciver() {
        return reciver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Message.reciver
     *
     * @param reciver the value for Message.reciver
     *
     * @mbg.generated
     */
    public void setReciver(Integer reciver) {
        this.reciver = reciver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Message.time
     *
     * @return the value of Message.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Message.time
     *
     * @param time the value for Message.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Message.content
     *
     * @return the value of Message.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Message.content
     *
     * @param content the value for Message.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}