package com.lemarket.data.model;

import java.util.Date;

public class Orderdetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetails.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetails.orderInfo
     *
     * @mbg.generated
     */
    private Integer orderinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetails.commodity
     *
     * @mbg.generated
     */
    private Integer commodity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetails.receive
     *
     * @mbg.generated
     */
    private Integer receive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetails.commodityType
     *
     * @mbg.generated
     */
    private Integer commodityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetails.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetails.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetails.id
     *
     * @return the value of OrderDetails.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetails.id
     *
     * @param id the value for OrderDetails.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetails.orderInfo
     *
     * @return the value of OrderDetails.orderInfo
     *
     * @mbg.generated
     */
    public Integer getOrderinfo() {
        return orderinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetails.orderInfo
     *
     * @param orderinfo the value for OrderDetails.orderInfo
     *
     * @mbg.generated
     */
    public void setOrderinfo(Integer orderinfo) {
        this.orderinfo = orderinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetails.receive
     *
     * @return the value of OrderDetails.receive
     *
     * @mbg.generated
     */
    public Integer getReceive() {
        return receive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetails.receive
     *
     * @param receive the value for OrderDetails.receive
     *
     * @mbg.generated
     */
    public void setReceive(Integer receive) {
        this.receive = receive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetails.commodity
     *
     * @return the value of OrderDetails.commodity
     *
     * @mbg.generated
     */
    public Integer getCommodity() {
        return commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetails.commodity
     *
     * @param commodity the value for OrderDetails.commodity
     *
     * @mbg.generated
     */
    public void setCommodity(Integer commodity) {
        this.commodity = commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetails.commodityTyoe
     *
     * @return the value of OrderDetails.commodityType
     *
     * @mbg.generated
     */
    public Integer getCommodityType() {
        return commodityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetails.commodityType
     *
     * @param commodityType the value for OrderDetails.commodityType
     *
     * @mbg.generated
     */
    public void setCommodityType(Integer commodityType) {
        this.commodityType = commodityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetails.count
     *
     * @return the value of OrderDetails.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetails.count
     *
     * @param count the value for OrderDetails.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetails.time
     *
     * @return the value of OrderDetails.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetails.time
     *
     * @param time the value for OrderDetails.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}