package com.lemarket.data.model;


import java.util.Date;

public class OrderWithDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.id
     *
     * @mbg.generated
     */
    private Orderdetails id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.user
     *
     * @mbg.generated
     */
    private Integer user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.price
     *
     * @mbg.generated
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.status
     *
     * @mbg.generated
     */
    private String status;
    public Orderdetails getId() {
        return id;
    }
    public void setId(Orderdetails id) {
        this.id = id;
    }
    public Integer getUser() {
        return user;
    }
    public void setUser(Integer user) {
        this.user = user;
    }
    public Float getPrice() {
        return price;
    }
    public void setPrice(Float price) {
        this.price = price;
    }
    public Date getTime() {
        return time;
    }
    public void setTime(Date time) {
        this.time = time;
    }
    public String getStatus() {
        return status;
    }
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

}
