package com.lemarket.data.model;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.owner
     *
     * @mbg.generated
     */
    private Integer owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.icon
     *
     * @mbg.generated
     */
    private Integer icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.phoneNumber
     *
     * @mbg.generated
     */
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.customerService
     *
     * @mbg.generated
     */
    private Integer customerservice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.servicePhoneNumber
     *
     * @mbg.generated
     */
    private String servicephonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.id
     *
     * @return the value of Shop.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.id
     *
     * @param id the value for Shop.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.owner
     *
     * @return the value of Shop.owner
     *
     * @mbg.generated
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.owner
     *
     * @param owner the value for Shop.owner
     *
     * @mbg.generated
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.name
     *
     * @return the value of Shop.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.name
     *
     * @param name the value for Shop.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.icon
     *
     * @return the value of Shop.icon
     *
     * @mbg.generated
     */
    public Integer getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.icon
     *
     * @param icon the value for Shop.icon
     *
     * @mbg.generated
     */
    public void setIcon(Integer icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.phoneNumber
     *
     * @return the value of Shop.phoneNumber
     *
     * @mbg.generated
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.phoneNumber
     *
     * @param phonenumber the value for Shop.phoneNumber
     *
     * @mbg.generated
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.customerService
     *
     * @return the value of Shop.customerService
     *
     * @mbg.generated
     */
    public Integer getCustomerservice() {
        return customerservice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.customerService
     *
     * @param customerservice the value for Shop.customerService
     *
     * @mbg.generated
     */
    public void setCustomerservice(Integer customerservice) {
        this.customerservice = customerservice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.servicePhoneNumber
     *
     * @return the value of Shop.servicePhoneNumber
     *
     * @mbg.generated
     */
    public String getServicephonenumber() {
        return servicephonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.servicePhoneNumber
     *
     * @param servicephonenumber the value for Shop.servicePhoneNumber
     *
     * @mbg.generated
     */
    public void setServicephonenumber(String servicephonenumber) {
        this.servicephonenumber = servicephonenumber == null ? null : servicephonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.description
     *
     * @return the value of Shop.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.description
     *
     * @param description the value for Shop.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}