package com.lemarket.data.model;

import java.util.Date;

public class Token {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Token.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Token.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Token.date_create
     *
     * @mbg.generated
     */
    private Date dateCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Token.validity
     *
     * @mbg.generated
     */
    private Integer validity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Token.id
     *
     * @return the value of Token.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Token.id
     *
     * @param id the value for Token.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Token.token
     *
     * @return the value of Token.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Token.token
     *
     * @param token the value for Token.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Token.date_create
     *
     * @return the value of Token.date_create
     *
     * @mbg.generated
     */
    public Date getDateCreate() {
        return dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Token.date_create
     *
     * @param dateCreate the value for Token.date_create
     *
     * @mbg.generated
     */
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Token.validity
     *
     * @return the value of Token.validity
     *
     * @mbg.generated
     */
    public Integer getValidity() {
        return validity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Token.validity
     *
     * @param validity the value for Token.validity
     *
     * @mbg.generated
     */
    public void setValidity(Integer validity) {
        this.validity = validity;
    }
}